server:
  port: 8080
datasource:
  host: 127.0.0.1
  port: 3306
  database: graduation
  username: root
  password: 123456
  charset: utf8
nlecloud:
  username: 18042409089
  password: 123456
  deviceId: 566636